springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

TILGANGSMASKINEN_SCOPE: dev-gcp.tilgangsmaskin.populasjonstilgangskontroll

FPSAK_SCOPE: dev-fss.teamforeldrepenger.fpsak
FPSAK_BASE_URL: https://fpsak-api.dev-fss-pub.nais.io

ENTRA_PROXY_SCOPE: dev-gcp.sikkerhetstjenesten.entra-proxy

TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851